#!/bin/sh
# aws ec2 script that will list ec2 instances on your default aws account
# based on flags and perform different actions

# import helper scripts
mydir="${0%/*}"
source "$mydir"/faws_sh/confirm.sh
source "$mydir"/faws_sh/awsec2/helper/get_instance.sh
source "$mydir"/faws_sh/awsec2/helper/get_region.sh
source "$mydir"/faws_sh/awsec2/ssh_instance.sh
source "$mydir"/faws_sh/awsec2/stop_instance.sh
source "$mydir"/faws_sh/awsec2/terminate_instance.sh

# help
function usage() {
  echo "usage: awsec2 <command> [-h] [-r] [-p]\n"
  echo "ssh/stop/terminate the selected instance\n"
  echo "<command>:\n"
  echo "ssh      \tssh to the selected instance if it is running\n"
  echo "         \twill start the instance if it is stopped\n"
  echo "stop     \tstop the selected instance if it is running\n"
  echo "terminate\tterminate the selected instance\n"
  echo "optional arguments:\n"
  echo "-h\tshow this help message and exit\n"
  echo "-r\tselect a region otherwise default region will be used\n"
  echo "-p\tspecify the path to look for keypair pem file"
}

# default args
action=''
selected_region=''
pem_location="$AWS_PEM"

# process the command to use
# shift to remove the command from the args
case "$1" in
  ssh)
    action='ssh'
    shift;;
  stop)
    action='stop'
    shift;;
  terminate)
    action='terminate'
    shift;;
esac

# process flags
while getopts ":rhp:" opt
do
  case "$opt" in
    r)
      # -r set a region to use, otherwise default region will be used
      echo "Select a region"
      selected_region=$(get_region)
      [[ -z "$selected_region" ]] && echo "No region selected" && exit 1;;
    p)
      # user specified path for pem file
      pem_location="$OPTARG";;
    h)
      # display usage and exit
      usage
      exit 0;;
    *)
      echo "Invalid option $OPTARG" >&2
      usage
      exit 1;;
  esac
done

[[ -z "$action" ]] && echo "No action command detected (ssh|stop|terminate)"

# get the instance data
# ${selected_instance} data format
# $1  $2      $3      $4
# id  status  keypair publicIp
selected_instance=$(get_instance "$selected_region")
instance_id=$(echo "$selected_instance" | awk '{print $1}')
instance_status=$(echo "$selected_instance" | awk '{print $2}')
instance_key_pem=$(echo "$selected_instance" | awk '{print $3 ".pem"}')
instance_ip_address=$(echo "$selected_instance" | awk '{print $4}')
# exit if no instance selected
[[ -z "$selected_instance" ]] && echo "No instance selected, exiting.." && exit 1
# default action, ssh into the instance
if [[ "$action" == 'ssh' ]]; then
  ssh_instance "$instance_id" "$instance_status" "$instance_key_pem" "$instance_ip_address" "$pem_location"
elif [[ "$action" == 'stop' ]]; then
  stop_instance "$instance_id" "$instance_status"
elif [[ "$action" == 'terminate' ]]; then
  terminate_instance "$instance_id"
else
  echo "$selected_instance"
fi
