#!/bin/sh
shopt -s nullglob
[[ -z "$AWS_PEM" ]] && echo "Please confiure your pem directory env var, instructions in README.md" && exit 1
[[ -z "$DOWNLOAD_LOCATION" ]] && echo "Please confiure your download location env var, instructions in README.md" && exit 1
cd $HOME/Downloads
for f in *
do
  pem_file=$(echo $f | awk -F "." '{
    if ($2 == "pem") {
      print $0
    }
  }')
  [[ -z "$pem_file" ]] && continue
  chmod 400 "$pem_file"
  mv -v "$pem_file" "$AWS_PEM/$pem_file"
  unset pem_file
done
