#!/bin/bash
#
# Main entry script of fzf.aws, used to route command to appropriate scripts
# @params
# Globals
#   $action_command: the command that decide which script to run
# Arguments
#   command: commands to run ec2/cform/keypair/s3 etc

# the directory of this script
mydir="${0%/*}"

function usage() {
  echo "help"
}

# if no argument are passed, display all available commands and show their help
if [[ -z "$@" ]]; then
  echo 'No action command detected'
  echo "Below are the available supported commands"
  # display all scripts in src folder and show their help message in fzf preview
  action_command=$(find "$mydir"/src -type f -depth 1 | \
    awk -F '/' '{print $NF}' | fzf --preview "$mydir/src/{} -h")
  [[ -z "$action_command" ]] && exit 0
  if [[ "$action_command" == 'keypair' ]]; then
    "${mydir}/src/${action_command}" -h
  else
    "$mydir/src/$action_command"
  fi
  exit 0
fi

# process the first argument and set action_command
action_command=''
case "$1" in
  s3)
    action_command='s3';;
  cform)
    action_command='cform';;
  keypair)
    action_command='keypair';;
  ec2)
    action_command='ec2';;
  help)
    usage
    exit 0;;
  -h)
    usage
    exit 0;;
  *)
    usage
    exit 1;;
esac
# clean/remove the first processed argument
shift

[[ -z "$action_command" ]] && exit 1

# run the script based on the first argument
# pass the rest of the argument to the new script
"$mydir/src/$action_command" "$@"
