#!/bin/sh

# current script directory
mydir="${0%/*}"

function usage() {
  echo "help"
}

# if no input display all available commands and show their help
if [[ -z "$@" ]]; then
  echo "Below are the available supported commands"
  find "$mydir"/src -type f -depth 1 | \
    awk -F '/' '{print $NF}' | \
    fzf --preview "$mydir/src/{} -h"
  exit 0
fi

aws_command=''
case "$1" in
  s3)
    aws_command='s3';;
  cform)
    aws_command='cform';;
  help)
    usage
    exit 0;;
  pem)
    aws_command='pem';;
  ec2)
    aws_command='ec2';;
  *)
    usage
    exit 1;;
esac
# finish processing the action argument
# remove the command from arg list
shift

echo "$@"
