#!/bin/sh
# aws ec2 script that will list ec2 instances on your default aws account
# @params
# $action_command: the command to run (ssh|stop|terminate|ls)
# $selected_region: the region if -r set
# $pem_location: location of the keypair file
# $user_name: username used to ssh into the instance
# $wait_flag: wait for command completion (instance running|stopped|terminated)
# $selected_instance: selected instance through fzf
  # $1  $2      $3      $4
  # id  status  keypair publicIp
# $instance_id: id of the instance
# $instance_status: start/stop/terminate/pending etc
# $instance_key_pem: keypair name
# $instance_ip_address: publicIp address

# import helper scripts
mydir="${0%/*}"
source "$mydir"/shsrc/confirm.sh
source "$mydir"/shsrc/ec2/helper/get_instance.sh
source "$mydir"/shsrc/ec2/helper/get_region.sh
source "$mydir"/shsrc/ec2/ssh_instance.sh
source "$mydir"/shsrc/ec2/stop_instance.sh
source "$mydir"/shsrc/ec2/terminate_instance.sh
source "$mydir"/shsrc/ec2/reboot_instance.sh
source "$mydir"/shsrc/ec2/usage.sh

# default args
action_command=''
selected_region=''
pem_location="$AWS_PEM"
user_name='ec2-user'
wait_flag='false'

# process the command to use
# shift to remove the command from the args
case "$1" in
  ssh)
    action_command='ssh'
    shift;;
  stop)
    action_command='stop'
    shift;;
  terminate)
    action_command='terminate'
    shift;;
  ls)
    action_command='ls'
    shift;;
  reboot)
    action_command='reboot'
    shift;;
esac

# process flags
while getopts ":rhp:u:w" opt
do
  case "$opt" in
    r)
      # -r set a region to use, otherwise default region will be used
      echo "Select a region"
      selected_region=$(get_region)
      [[ -z "$selected_region" ]] && echo "No region selected" && exit 1;;
    p)
      # user specified path for pem file
      pem_location="$OPTARG";;
    h)
      # display usage and exit
      usage "$action_command"
      exit 0;;
    u)
      user_name="$OPTARG";;
    w)
      wait_flag='true';;
    *)
      echo "Invalid option $OPTARG" >&2
      usage "$action_command"
      exit 1;;
  esac
done

# display fzf menu for available_commands when no action detected
if [[ -z "$action_command" ]]; then
  echo "No action command detected"
  echo "Below are the available supported commands"
  available_commands=(ssh stop terminate ls)
  help_commands=$(printf '%s\n' "${available_commands[@]}" | fzf --preview "$mydir/ec2 {} -h")
  usage "$help_commands"
  exit 0
fi

# get the instance data
# ${selected_instance} data format
# $1  $2      $3      $4
# id  status  keypair publicIp
selected_instance=$(get_instance "$selected_region")
instance_id=$(echo "$selected_instance" | awk '{print $1}')
instance_status=$(echo "$selected_instance" | awk '{print $2}')
instance_key_pem=$(echo "$selected_instance" | awk '{print $3 ".pem"}')
instance_ip_address=$(echo "$selected_instance" | awk '{print $4}')
# exit if no instance selected
[[ -z "$selected_instance" ]] && echo "No instance selected, exiting.." && exit 1
# default action_command, ssh into the instance
if [[ "$action_command" == 'ssh' ]]; then
  ssh_instance "$instance_id" "$instance_status" "$instance_key_pem" "$instance_ip_address" "$pem_location" "$user_name" "$wait_flag"
elif [[ "$action_command" == 'stop' ]]; then
  stop_instance "$instance_id" "$instance_status" "$wait_flag"
elif [[ "$action_command" == 'terminate' ]]; then
  terminate_instance "$instance_id" "$wait_flag"
elif [[ "$action_command" == 'ls' ]]; then
  echo "$selected_instance"
elif [[ "$action_command" == 'reboot' ]]; then
  reboot_instance "$instance_id"
fi
